### ISSUE TITLE
problems with pane‐positioning

### ISSUE THREAD

**Issue by Zambonifofex** [banacorn/agda-mode#83]
If I choose to dock the `agda-mode` info‐display‐thingie as a pane (to the right, for example), I encounter a couple of problems:

+ I cannot scroll the information at all.
+ If I close a file, the corresponding info‐display‐thingie doesn’t necessarily close when I have multiple Agda files open.

I was able to work around the first one by having this on my `styles.less` file:

```less
.agda-mode > section
{
	display: grid;
	place-items: start stretch;
	align-content: start;
}

.agda-body-container
{
	place-self: stretch;
	min-width: 0;
	word-wrap: break-word;
	min-height: 0;
}

.agda-body
{
	max-height: 100%;
}
```
