### ISSUE TITLE
use user editor font information

### ISSUE THREAD

**Issue by Zambonifofex** [banacorn/agda-mode#85]
I’m one of those crazy weirdos who happen to prefer to write programs in a proportional typeface. It would be really cool if the package could respect the font I chose for my editor.

I was able to do this myself by having the following in my `styles.less` file, but I feel like it would be preferable if this was done by the package itself.

```less
.agda-body-container
{
	font-family: var(--editor-font-family) !important;
	font-size: var(--editor-font-size) !important;
	line-height: var(--editor-line-height) !important;
}
```
